modLoader="javafml" #mandatory
loaderVersion="[46,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GNU LESSER GENERAL PUBLIC LICENSE"
issueTrackerURL="https://github.com/AlexModGuy/Mediumcore/issues" #optional
[[mods]] #mandatory
modId="mediumcore" #mandatory
version="1.0.0" #mandatory
displayName="Mediumcore" #mandatory
displayURL="" #optional
logoFile="assets/mediumcore/textures/mod_logo.png" #optional
authors="Alexthe668" #optional
description='''A difficulty between normal survival and hardcore.'''
[[dependencies.mediumcore]]
modId="forge"
mandatory=false
versionRange="[47.1.3,)"
ordering="NONE"
side="BOTH"
